import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google"; // це гугл шрифти які можна використовувати в next.js. Декілька шрифтів можна використовувати одночасно через кому. Це зроблено для того, щоб не було зайвих запитів на сервер.
import { Providers } from "@/components/Providers/Providers";

const inter = Inter({ subsets: ["latin"] }); // це шрифт inter з підмножиною latin
const roboto = Roboto({ weight: "300", subsets: ["cyrillic-ext"] }); // це шрифт roboto з підмножиною cyrillic-ext

// перемінна metadata буде містити в собі мета теги. це впливає на пошукові системи і соціальні мережі (SEO). Це можна додавати на будь яку сторінку
export const metadata: Metadata = {
  title: "NEXT Learning",
  description: "Generated by create next app",
};

// Це головний файл, який буде використовуватися на всіх сторінках
export default function RootLayout({
  children, // це буде вміщати в себе всі сторінки
}: {
  children: React.ReactNode; // це буде вміщати в себе всі сторінки
}) {
  // тут можуть бути будь які мета теги:
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </Providers>
      </body>
      {/* тут відповідно на наші класи вішаються наші шрифти */}
    </html>
  );
}
